# Generated by Django 3.0.3 on 2020-04-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('siglas', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('a_paterno', models.CharField(max_length=255)),
                ('a_materno', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
