# Generated by Django 3.0.3 on 2020-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Externo',
            fields=[
                ('id_externo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('a_paterno', models.CharField(max_length=255)),
                ('a_materno', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, unique=True)),
            ],
        ),
    ]
