# Generated by Django 3.0.3 on 2020-04-24 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0002_cat_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_serie', models.CharField(max_length=128, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='fecha ingreso')),
                ('is_active', models.BooleanField(default=True)),
                ('mac_address', models.CharField(max_length=15, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('motivo_baja', models.TextField()),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('area_it', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('extension', models.IntegerField(null=True)),
                ('nombre_ext', models.CharField(max_length=255)),
                ('id_telefono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bienes.Bien')),
            ],
        ),
        migrations.CreateModel(
            name='Resguardo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('observaciones', models.TextField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.Bien')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.Cat_Categoria'),
        ),
        migrations.AddField(
            model_name='bien',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='externo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Cat_Externo'),
        ),
        migrations.AddField(
            model_name='bien',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes.Cat_Marca'),
        ),
        migrations.AddField(
            model_name='bien',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes.Cat_Modelo'),
        ),
        migrations.AddField(
            model_name='bien',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes.Cat_Proveedor'),
        ),
    ]
